# Generated by Django 4.0.5 on 2022-07-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mail_id', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('facebook_id', models.CharField(max_length=100)),
                ('twitter_id', models.CharField(max_length=100)),
                ('instagram_id', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank='TRUE', null='TRUE', upload_to='images/')),
                ('area', models.FloatField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('oname', models.CharField(default='NULL', max_length=500)),
                ('oaddress', models.CharField(default='NULL', max_length=2000)),
                ('omail', models.EmailField(default='NULL', max_length=100)),
                ('ophone', models.CharField(default='NULL', max_length=100)),
            ],
        ),
    ]
